sonar.projectKey=devops-ci-cd-health-api
sonar.projectName=DevOps CI/CD Health API

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.js

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
